version: "3"
services:
  reverse-proxy:
    image: nginx
    restart: unless-stopped
    ports:
      - 80:80
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./static:/usr/share/nginx/html

  backend:
    build: .
    restart: unless-stopped
    volumes:
      - ./:/app
